// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEzrCLDu8xNtMx3MHwPKu4Q42PHtd3UU0',
    appId: '1:754340320617:web:d28dd1a45d11eb52a259f8',
    messagingSenderId: '754340320617',
    projectId: 'tasky-102e1',
    authDomain: 'tasky-102e1.firebaseapp.com',
    storageBucket: 'tasky-102e1.firebasestorage.app',
    measurementId: 'G-TR4KRCJB0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdXTfXKWLsyTPFRhM4RthAX-W7TvkNnn0',
    appId: '1:754340320617:android:54ff78a22c587bc8a259f8',
    messagingSenderId: '754340320617',
    projectId: 'tasky-102e1',
    storageBucket: 'tasky-102e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqzz3esoC5nS4JfKbka5ReSh717JgFUg',
    appId: '1:754340320617:ios:1d531548a43db7a7a259f8',
    messagingSenderId: '754340320617',
    projectId: 'tasky-102e1',
    storageBucket: 'tasky-102e1.firebasestorage.app',
    iosBundleId: 'com.example.taskeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtqzz3esoC5nS4JfKbka5ReSh717JgFUg',
    appId: '1:754340320617:ios:1d531548a43db7a7a259f8',
    messagingSenderId: '754340320617',
    projectId: 'tasky-102e1',
    storageBucket: 'tasky-102e1.firebasestorage.app',
    iosBundleId: 'com.example.taskeyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEzrCLDu8xNtMx3MHwPKu4Q42PHtd3UU0',
    appId: '1:754340320617:web:42ae91b49cf8ea02a259f8',
    messagingSenderId: '754340320617',
    projectId: 'tasky-102e1',
    authDomain: 'tasky-102e1.firebaseapp.com',
    storageBucket: 'tasky-102e1.firebasestorage.app',
    measurementId: 'G-CYKFMDLXMW',
  );
}
